name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install black isort ruff
      - name: Lint backend
        run: |
          ruff check backend
          black --check backend
          isort --check backend
      - name: Install frontend deps
        run: |
          cd frontend
          npm install
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      - name: Install Linux desktop dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libgdk-pixbuf-2.0-0 \
            librsvg2-dev \
            libayatana-appindicator3-dev \
            libsoup2.4-dev
          if ! sudo apt-get install -y libjavascriptcoregtk-4.1-dev; then
            sudo apt-get install -y libjavascriptcoregtk-4.0-dev
          fi
          if ! sudo apt-get install -y libwebkit2gtk-4.1-dev; then
            sudo apt-get install -y libwebkit2gtk-4.0-dev
          fi
      - name: Cargo check (Tauri)
        run: |
          cd tauri
          npm install
          npm run tauri build -- --debug
